version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "update:"
    target-branch: "main"
    allow:
      - dependency-type: "direct"
    versioning-strategy: increase
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint-plugin-unused-imports"
    ignore:
      - dependency-name: "conventional-changelog-conventionalcommits"
        update-types: ["version-update:semver-major"]
  
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "update(action):"
    target-branch: "main"
