version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "update:"
    target-branch: "main"
    allow:
      - dependency-type: "direct"
    versioning-strategy: increase
  
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "update(action):"
    target-branch: "main"
